on:
  push:
    branches:
      - "main"

name: Release

concurrency:
  group: release
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        id: toolchain
        with:
          profile: minimal
          toolchain: 1.60.0
          target: wasm32-unknown-unknown
          override: true
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ steps.toolchain.outputs.rustc_hash }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: jetli/wasm-bindgen-action@v0.2.0
        with:
          version: "latest"
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target wasm32-unknown-unknown
      - run: wasm-bindgen --out-dir "./out/" --target web "./target/wasm32-unknown-unknown/release/game.wasm"
      - run: cp -r assets docs/
      - run: cp out/game_bg.wasm out/game.js docs/
      - uses: EndBug/add-and-commit@v9
        with:
          add: "docs"
          default_author: github_actions
          new_branch: gh-pages
          push: "--force origin gh-pages"
