on:
  push:
    branches:
      - "main"

name: Release

concurrency:
  group: release
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: wasm32-unknown-unknown
          override: true
      - uses: jetli/wasm-bindgen-action@v0.1.0
        with:
          version: "latest"
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target wasm32-unknown-unknown
      - run: wasm-bindgen --out-dir "./out/" --target web "./target/wasm32-unknown-unknown/release/game.wasm"
      - run: cp -r assets web/
      - run: cp out/game_bg.wasm out/game.js web/
      - uses: EndBug/add-and-commit@v9
        with:
          add: "web"
          default_author: github_actions
          new_branch: gh-pages
          push: "--force origin gh-pages"
